services:
  cheatshield-face-detect:
    container_name: cheatshield-face-detect
    image: ghcr.io/integer-class/cheatshield-face-detect:main
    volumes:
      - ./workspace:/app/workspace
    networks:
      - cheatshield-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 1024MB
          cpus: "0.75"
        reservations:
          memory: 400MB
          cpus: "0.20"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.services.cheatshield-face-detect.loadBalancer.server.port=8000"
      - "traefik.http.services.cheatshield-face-detect.loadBalancer.server.scheme=http"
      - "traefik.http.routers.cheatshield-face-detect.rule=Host(`cheatshield-face-detect.elianiva.my.id`)"
      - "traefik.http.routers.cheatshield-face-detect.tls.certresolver=tlsresolver"
      - "traefik.http.routers.cheatshield-face-detect.entrypoints=web,websecure"
      - "traefik.http.routers.cheatshield-face-detect.middlewares=cheatshield-face-detect-compress,cheatshield-face-detect-redirect,cheatshield-face-detect-limiter"
      - "traefik.http.middlewares.cheatshield-face-detect-compress.compress=true"
      - "traefik.http.middlewares.cheatshield-face-detect-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.cheatshield-face-detect-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.cheatshield-face-detect-limiter.ratelimit.average=200"
      - "traefik.http.middlewares.cheatshield-face-detect-limiter.ratelimit.burst=100"
      - "traefik.http.middlewares.cheatshield-face-detect-limiter.ratelimit.period=1s"
    platform: linux/amd64

networks:
  cheatshield-network:
    external: true
