services:
  cheatshield-admin:
    container_name: cheatshield-admin
    image: ghcr.io/integer-class/cheatshield-admin:main
    networks:
      - cheatshield-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 30s
        window: 120s
      resources:
        limits:
          memory: 1024MB
          cpus: "0.75"
        reservations:
          memory: 400MB
          cpus: "0.20"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.services.cheatshield-admin.loadBalancer.server.port=80"
      - "traefik.http.services.cheatshield-admin.loadBalancer.server.scheme=http"
      - "traefik.http.routers.cheatshield-admin.rule=Host(`cheatshield-admin.elianiva.my.id`)"
      - "traefik.http.routers.cheatshield-admin.tls.certresolver=tlsresolver"
      - "traefik.http.routers.cheatshield-admin.entrypoints=web,websecure"
      - "traefik.http.routers.cheatshield-admin.middlewares=cheatshield-admin-compress,cheatshield-admin-redirect,cheatshield-admin-limiter"
      - "traefik.http.middlewares.cheatshield-admin-compress.compress=true"
      - "traefik.http.middlewares.cheatshield-admin-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.cheatshield-admin-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.cheatshield-admin-limiter.ratelimit.average=200"
      - "traefik.http.middlewares.cheatshield-admin-limiter.ratelimit.burst=100"
      - "traefik.http.middlewares.cheatshield-admin-limiter.ratelimit.period=1s"
    platform: linux/amd64

networks:
  cheatshield-network:
    external: true
