services:
  postgresql:
    container_name: postgresql-db
    image: postgres:17.2
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - cheatshield-network
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  cheatshield-network:
    external: true

