name: Build Admin

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/cd-admin.yml"
      - "cheatshield-admin/**"

jobs:
  cd:
    name: Build Image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # shallow clone for faster checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-admin
          flavor: |
            latest=false
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./cheatshield-admin"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}-build
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-build
          build-args: |
            ENV=production
            DOTENV_PRIVATE_KEY=${{ secrets.DOTENV_PRIVATE_KEY }}
          outputs: type=image,compression=zstd,compression-level=3
          platforms: linux/amd64
          provenance: false
